os:
  - linux

language: crystal

crystal:
  - latest

script:
  - crystal spec
  - crystal docs

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
